services:
  - type: web
    name: skiniq-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: skiniq_prod_db
      - key: SECRET_KEY
        generateValue: true
