"""add_initiator_id_to_professional_connections

Revision ID: 47554fb00c95
Revises: 8b9c0d1e2f3a
Create Date: 2026-10-07 20:05:08.954180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47554fb00c95'
down_revision: Union[str, Sequence[str], None] = '8b9c0d1e2f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_messages_is_read'), 'chat_messages', ['is_read'], unique=False)
    op.drop_constraint(op.f('ingredients_name_key'), 'ingredients', type_='unique')
    op.drop_index(op.f('idx_prod_rec_user_created'), table_name='product_recommendations')
    op.create_index(op.f('ix_product_recommendations_assessment_id'), 'product_recommendations', ['assessment_id'], unique=False)
    op.add_column('professional_connections', sa.Column('initiator_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_prof_connections_referred_by'), table_name='professional_connections')
    op.create_index(op.f('ix_professional_connections_initiator_id'), 'professional_connections', ['initiator_id'], unique=False)
    op.create_index(op.f('ix_professional_connections_referred_by_id'), 'professional_connections', ['referred_by_id'], unique=False)
    op.create_foreign_key('fk_prof_connections_initiator', 'professional_connections', 'users', ['initiator_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_professional_recommendations_connection_id'), 'professional_recommendations', ['connection_id'], unique=False)
    op.drop_constraint(op.f('progress_snapshots_assessment_id_key'), 'progress_snapshots', type_='unique')
    op.create_index(op.f('ix_progress_snapshots_assessment_id'), 'progress_snapshots', ['assessment_id'], unique=True)
    op.drop_constraint(op.f('skin_scores_assessment_id_key'), 'skin_scores', type_='unique')
    op.create_index(op.f('ix_skin_scores_assessment_id'), 'skin_scores', ['assessment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skin_scores_assessment_id'), table_name='skin_scores')
    op.create_unique_constraint(op.f('skin_scores_assessment_id_key'), 'skin_scores', ['assessment_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_progress_snapshots_assessment_id'), table_name='progress_snapshots')
    op.create_unique_constraint(op.f('progress_snapshots_assessment_id_key'), 'progress_snapshots', ['assessment_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_professional_recommendations_connection_id'), table_name='professional_recommendations')
    op.drop_constraint('fk_prof_connections_initiator', 'professional_connections', type_='foreignkey')
    op.drop_index(op.f('ix_professional_connections_referred_by_id'), table_name='professional_connections')
    op.drop_index(op.f('ix_professional_connections_initiator_id'), table_name='professional_connections')
    op.create_index(op.f('ix_prof_connections_referred_by'), 'professional_connections', ['referred_by_id'], unique=False)
    op.drop_column('professional_connections', 'initiator_id')
    op.drop_index(op.f('ix_product_recommendations_assessment_id'), table_name='product_recommendations')
    op.create_index(op.f('idx_prod_rec_user_created'), 'product_recommendations', ['user_id', 'created_at'], unique=False)
    op.create_unique_constraint(op.f('ingredients_name_key'), 'ingredients', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_chat_messages_is_read'), table_name='chat_messages')
    # ### end Alembic commands ###
